# Generated by Django 4.0.6 on 2022-07-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0005_group_users_alter_group_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='urgent',
            field=models.IntegerField(choices=[(1, 'nieważne'), (2, 'mało ważne'), (3, 'normaln'), (4, 'ważne'), (5, 'Super ważne')], default=3),
        ),
    ]
